[[language]]
name = "rust"
auto-format = true

roots = [
	"Cargo.toml",
	"Cargo.lock"
]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.rust-analyzer.config]
check = { command = "clippy" }
